#!/bin/bash

set -o nounset
set -o errexit
set -o pipefail

function symlink {
  chmod 660 $(pwd)/$1
  chmod 660 $2
  ln -s -f -v $(pwd)/$1 $2 | sed -e 's/[‘’]//g' 
}

symlink dot-vim/vimrc ~/.vimrc

symlink dot-fish/config.fish ~/.config/fish/config.fish

symlink dot-hammerspoon/init.lua ~/.hammerspoon/init.lua

symlink dot-git/gitconfig ~/.gitconfig

symlink dot-git/gitignore_global ~/.gitignore_global

symlink dot-spacemacs/spacemacs ~/.spacemacs

echo -e "\n[done]"
