export PATH=/usr/local/sbin:$PATH

if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

if [-f ~/.secret_profile ]; then
  # export AWS_ACCESS_KEY_ID=""
  # export AWS_SECRET_KEY=""
  # export AWS_SECRET_ACCESS_KEY=""
  . ~/.secret_profile
fi

# Django development
export DEVELOPMENT=1

